[workspace]
resolver = "2"
members = ["crates/*"]

[profile.reldbg]
inherits = "release"
debug = true
lto = "fat"
incremental = true

[profile.release2]
inherits = "release"
opt-level = 3
debug = false
strip = true
lto = true
codegen-units = 1
incremental = false
panic = "abort"

[patch.crates-io]
compio = { git = "https://github.com/three014/compio.git" }
compio-buf = { git = "https://github.com/three014/compio.git" }
compio-io = { git = "https://github.com/three014/compio.git" }
compio-driver = { git = "https://github.com/three014/compio.git" }
compio-quic = { git = "https://github.com/three014/compio.git" }
compio-runtime = { git = "https://github.com/three014/compio.git" }
