[package]
name = "qusb"
version = "0.1.0"
edition = "2021"

[dependencies]
quinn = { version = "0.11.6" }
thiserror = "2.0.3"
tokio = { version = "1.41.1", default-features = false, features = [
    "io-util",
    "sync",
    "macros",
    "rt",
] }
proto = { package = "qusb-proto", path = "../qusb-proto" }
nohash-hasher = "0.2.0"
rand = "0.8.5"
tracing = "0.1.40"
tokio-util = { version = "0.7.12", default-features = false }
nusb = "0.1.12"
vhci = { package = "usb_vhci", git = "https://github.com/three014/usb_vhci", features = ["zerocopy"], version = "0.2.0" }
bytes = "1.9.0"
zerocopy = "0.8.13"
rusb = { git = "https://github.com/three014/rusb.git", version = "0.9.4" }
fxhash = "0.2.1"
rusb_async = { git = "https://github.com/three014/rusb-async.git", version = "0.3.0" }

[dev-dependencies]
tracing-test = { version = "0.2.5" }
tracing-subscriber = "0.3.19"
