[package]
name = "qusb-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["wrap_help", "derive"] }
compio-macros = "0.1.2"
compio-runtime = { version = "0.7.0", default-features = false, features = ["io-uring"] }
compio-signal = "0.5.0"
qusb = { path = "../qusb" }
rcgen = "0.13.2"
rustls = { version = "0.23.25", default-features = false }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
